"""
Generate starter ML project folders and files
"""

import os


def generate_scaffold(base_path: str, project_name: str) -> str:
    """
    Create a minimal project scaffold:
      base_path/
        project_name/
            data/
            notebooks/
            src/
            README.md
    """

    project_path = os.path.join(base_path, project_name)

    # Define directory structure
    folders = [
        os.path.join(project_path, "data"),
        os.path.join(project_path, "notebooks"),
        os.path.join(project_path, "src"),
    ]

    # Create folders
    for folder in folders:
        os.makedirs(folder, exist_ok=True)

    # Add starter README
    readme_path = os.path.join(project_path, "README.md")
    with open(readme_path, "w") as f:
        f.write(f"# {project_name}\n\nStarter project generated by MLE-Agent.")

    return f"Project scaffold created at: {project_path}"